### ISSUE TITLE
Which Docker binary?

### ISSUE THREAD

**Issue by 000generic** [h836472/ContScout#10]
I was unclear after reading things over - which of the Docker binaries do you recommend:

From github main page:
docker pull h836472/contscout:develop

From github manual:
docker pull h836472/contscout:latest

Both ReadMe documents look to have been updated 3 months ago, so I wasn't sure which of the two binaries to use (I initially downloaded develop). 

I'm looking forward to giving ContScout a try!

Thank you :) Eric

**Comment by h836472** [comment]
Dear Eric,

Currently, there are 4 ContScout branches. Two of them are frozen, to
represent the exact version corresponding to various manuscript versions
(1x bioRxiv, 1x NatComm). Then, there is the "develop" version that is
supposed to hold the most recent features ready for testing. Finally, there
is the "latest" version that corresponds to the most latest stable and
final version meant to be used by the community.
Normally (for potentially better stability and better validation) I would
recommend to use docker pull h836472/contscout:*latest*. However, I have
just checked ContScout and updateDB within the latest and devel branch
images and right now they are the same. You are good to go with the
development version too.
Sorry for the confusion on the Github documentation, I shall set all
instruction to :latest.

Balázs.

**Comment by 000generic** [comment]
Awesome!  Thank you so much :)

**Comment by h836472** [comment]
Dear Eric,

No prob, thank you for spotting the inconsistency within the documentation.
Version references have been sorted out at GitHub,

Balazs
