### ISSUE TITLE
Singularity image

### ISSUE THREAD

**Issue by Sanrrone** [h836472/ContScout#3]
Hi!,
Is there a way to have the image in singularity format? as we work in a HPC Docker is not allowed

thanks in advance!

**Comment by Sanrrone** [comment]
Never mind, I found it in the reppo.

**Comment by h836472** [comment]
Dear Sandro,

You can always use singularity to fetch an image from the docker repository
and convert it to a local singularity file (sif).
Please decide which version to use (suggestion: natcomm, that is linked to
the published article.)

Here is the command, to build your own local .sif file
*singularity build contscout_natcomm.sif docker://h836472/contscout:natcomm*

Then, you can run ContScout with the following command:
*singularity exec **contscout_natcomm.sif ContScout -h*

*This shall show you the help message with available parameters.*

When running the tool, please do not forget to add some write-able host
directories to your singularity container using the -B switch

example database download command, for the "toy" *swissprot* database

*formula*
*singularity exec -B <local_database_directory>:/databases -B
<local_tmp_folder>:/tmp updateDB -u /databases --dbname swissprot*

*example*
*singularity exec -B /users/h836472/databases:/databases -B /SSD/temp:/tmp
updateDB -u /databases --dbname swissprot*

This shall download and install the swissprot database for you. Please
note, this database is for testing only. For your real-life data, you will
need a more comprehensive database such as nr, refseq, uniprotKB uniref90
or uniref100
*. *

Note that these large databases can take several hours to download and
build. Be careful to allow enough runtime (walltime) for the node on the
HPC to proceed with the download and conversions.

Fingers crossed for the setup and running of the tool, if you need any help
please let me know.

Balazs
