### ISSUE TITLE
[New feature] propagate decontamination to contigs

### ISSUE THREAD

**Issue by Sanrrone** [h836472/ContScout#9]
Dear Balazs,
I was wondering if it is possible to remove the contaminated genes/proteins from the original contigs. I have the filtered outputs which are the proteins. However, it would be useful to have the decontaminated scaffolds as well for further analyses. Is there a way to propagate the filters to the original contigs? I was thinking in hardcoding the .gff and the original .fna to break down the contigs.
Is there an option for that or the output of the pipeline is until the filtered proteins?

Thank you very much in advance,
Sandro

**Comment by h836472** [comment]
Dear Sandro,

To some extent, the function you describe is already available in
ContScout. With the -G / --genome_filter switch, contigs that are tagged at
the consensus call step as contaminationare removed from the DNA fasta and
corresponding annotation GxF files. At the same time, currently, there is
no option for the selective masking of individual "alien-looking" genes
within those contigs that are labeled as non_contaminant at the consensus
call stage.

Hope this explanation helps,

Balazs
